name: CI Pipeline

on:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#push
  push:
    branches:
      - gitea-ci
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch: # allow manual trigger

env:
  IMAGE_NAME: mcp-crawl4ai
  NAMESPACE: open-webui
  # CI_DEBUG: 600

defaults:
  run:
    shell: bash

# https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
jobs:
  build:
    # run directly in the runner container in host mode
    # so that `dind` container won't have to separately
    # repull al2023-devops image that's already on host
    runs-on: al2023-devops
    steps:
      # https://github.com/actions/checkout
      - name: Check out Git Repo
        id: checkout
        uses: actions/checkout@v6

      # https://github.com/erhhung/homelab-k8s/tree/main/files/gitea/runner/ciutils.sh
      - name: Log in to Registry
        id: login
        run: buildah_login

      - name: Build Docker Image
        id: build
        run: buildah_build $IMAGE_NAME --no-cache -f ./Dockerfile .

      - name: Push Docker Image
        id: push
        run: buildah_push $IMAGE_NAME $GIT_COMMIT_SHORT_SHA

  deploy:
    runs-on: al2023-devops
    needs: build
    steps:
      - name: Prepare to Deploy
        id: prepare
        # $GIT_COMMIT_SHORT_SHA is only available after first run
        # step in each job, exported by "/ci/scripts/ci-utils.sh"
        run: export_env IMAGE "$CI_REGISTRY_PATH/$IMAGE_NAME:$GIT_COMMIT_SHORT_SHA"

      # Gitea Actions does not support
      # variable expansion in step name
      - name: Deploy mcpo
        env:
          COMPONENT: mcpo
        run: |
          set_k8s_image Deployment $NAMESPACE $COMPONENT container crawl4ai $IMAGE
          kubectl rollout restart Deployment -n $NAMESPACE $COMPONENT
