# https://buildkite.com/docs/pipelines/configure/defining-steps#step-defaults
agents:
  queue: kubernetes
env:
  # `$GIT_COMMIT_SHORT_SHA` is set by
  # agent pod /ci/scripts/ci-utils.sh
  IMAGE_NAME: mcp-crawl4ai
  NAMESPACE: open-webui

steps:
  - label: ":hammer: Build"
    command: .buildkite/build.sh
  - label: ":kubernetes: Deploy"
    command: .buildkite/deploy.sh
